---
- hosts: localhost
  become: true
  gather_facts: yes

  vars:
    mounts:
      PublicShare:
        share: 10.1.1.251:/mnt/public
        mount: /opt/publicshare
        type: nfs
        options: auto
        automount: true

  roles:
    - role: nfs-client