---
- hosts: all
  become: true
  gather_facts: yes

  vars:
    mounts:
      PublicShare:
        # Added ip server, which create throught vagrant
        share: 192.168.56.251:/mnt/public
        mount: /opt/publicshare
        type: nfs
        options: auto
        automount: true

  roles:
    - role: nfs-client